# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8963fe88-516f-4f8c-b073-9769dbe8203f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8963fe88-516f-4f8c-b073-9769dbe8203f".device = "/dev/disk/by-uuid/8963fe88-516f-4f8c-b073-9769dbe8203f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ECD2-EEE8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-692243f3-3acf-44f2-a9c8-8b4b82967a77"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
